Assignment 1/Models/BookingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment_1.Models
{
    public class BookingViewModel
    {
        public Bookings Bookings { get; set; }
        public Event Event { get; set; }

    }
}

Assignment 1/Models/Bookings.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Assignment_1.Models
{
    public class Bookings
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BookingId { get; set; }


        [Required]
        public String RaceType { get; set; }

        [Required]
        public bool Status { get; set; }


        public virtual ApplicationUser ApplicationUser { get; set; }

        [Required]
        public virtual Event Event { get; set; }

       
    }
}

Assignment 1/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment_1.Common;
using Assignment_1.Models;
using Microsoft.AspNet.Identity;

namespace Assignment_1.Views
{
    [Authorize(Roles ="Runner")]
    public class BookingController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        public ActionResult EventBooking() {

            ApplicationUser user = db.Users.Find(User.Identity.GetUserId());

            return View(db.Bookings.Where(b=> b.ApplicationUser.Id == user.Id).ToList());


        }




        // GET: Booking/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Get the event with the Id
            Event @event = db.Event.Find(id);

            if (@event == null)
            {
                return HttpNotFound();
            }

            if (@event.DateOfEvent < DateTime.Now)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }


            // Get user bookings if available 

            String userId =  User.Identity.GetUserId();

            Bookings bookings = db.Bookings.Where(b => b.Event.EventId == id
            && b.ApplicationUser.Id == userId).FirstOrDefault();

            BookingViewModel bookingViewModel = new BookingViewModel();

            if (bookings == null)
            {

                List<EventTypeSelector> eventTypeSelector = new List<EventTypeSelector>();


                if (@event.FivekmRace)
                {
                    EventTypeSelector eventTypeSelector_ob = new EventTypeSelector();
                    eventTypeSelector_ob.TypeName = "5KM Race";
                    eventTypeSelector_ob.Typevalue = "1";
                    eventTypeSelector.Add(eventTypeSelector_ob);
                }
                if (@event.TenkmRace)
                {
                    EventTypeSelector eventTypeSelector_ob = new EventTypeSelector();
                    eventTypeSelector_ob.TypeName = "10KM Race";
                    eventTypeSelector_ob.Typevalue = "2";
                    eventTypeSelector.Add(eventTypeSelector_ob);
                }
                if (@event.HalfMarathon)
                {
                    EventTypeSelector eventTypeSelector_ob = new EventTypeSelector();
                    eventTypeSelector_ob.TypeName = "Half Matahhon";
                    eventTypeSelector_ob.Typevalue = "3";
                    eventTypeSelector.Add(eventTypeSelector_ob);
                }
                if (@event.FullMarathon)
                {
                    EventTypeSelector eventTypeSelector_ob = new EventTypeSelector();
                    eventTypeSelector_ob.TypeName = "Full Matahhon";
                    eventTypeSelector_ob.Typevalue = "4";
                    eventTypeSelector.Add(eventTypeSelector_ob);
                }


                ViewBag.EventType = new SelectList(eventTypeSelector, "TypeValue", "TypeName");
                bookingViewModel.Bookings = bookings;
                bookingViewModel.Event = @event;

                return View(bookingViewModel);
            }

            else
            {
                
                bookingViewModel.Bookings = bookings;
                bookingViewModel.Event = @event;
                return View(bookingViewModel);
            }

            
        }



        // GET: Booking/Create
        public ActionResult Cancel(int? id)
        {
            String UserId = User.Identity.GetUserId();


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Bookings booking = db.Bookings.Where(m => m.ApplicationUser.Id == UserId && m.Event.EventId == id).FirstOrDefault();


            if (booking == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            

            Event @event = db.Event.Find(booking.Event.EventId);


            if (@event == null)
            {
                return HttpNotFound();
            }

            if (@event.DateOfEvent <= DateTime.Now)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }


            if (!booking.Status)
            {
                return RedirectToAction("Details", new { id = booking.Event.EventId });

            }


            booking.Status = false;
            db.Entry(booking).State = EntityState.Modified;
            db.SaveChanges();


            String toEmail = booking.ApplicationUser.Email;
            String subject = "You Have Cancelled Booking For " + booking.Event.EventName;
            String contents = CreateCancelBody(booking);

            EmailSender es = new EmailSender();
            es.Send(toEmail, subject, contents, "Run 360 Event Cancellation");

            ViewBag.Result = "Email has been send.";




            return RedirectToAction("Details", new { id = booking.Event.EventId } );


        }



        // POST: Booking/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "RaceType, Event")] Bookings bookings, String btn)
        {

            var eventId = int.Parse(btn);

            bookings.Event = db.Event.Find(eventId);

            ModelState.Clear();
            TryValidateModel(bookings);

            if (ModelState.IsValid)
            {
               
               if (bookings.RaceType == "1")
                {
                    bookings.RaceType = "5KM Race";
                }
               else if(bookings.RaceType == "2")
                {
                    bookings.RaceType = "10KM Race";
                }
               else if (bookings.RaceType == "3")
                {
                    bookings.RaceType = "Half marathon";
                }
               else
                {
                    bookings.RaceType = "Full Marathon";
                }

                bookings.ApplicationUser = db.Users.Find(User.Identity.GetUserId());

                bookings.Status = true;

                db.Bookings.Add(bookings);

                db.SaveChanges();


                String toEmail = bookings.ApplicationUser.Email;
                String subject = "You Have Successfully Registered For " + bookings.Event.EventName;
                String contents = CreateBody(bookings);

                EmailSender es = new EmailSender();
                es.Send(toEmail, subject, contents, "Run 360 Event Booking");

                ViewBag.Result = "Email has been send.";


                return RedirectToAction("Details");
            }

            return RedirectToAction("Details");
        }




        private String CreateBody(Bookings booking) {

            String body = String.Empty;
            using (StreamReader reader = new StreamReader(Server.MapPath("~/Email Templates/index.html")))
            {

                body = reader.ReadToEnd();

            }


            body = body.Replace("{Event}", booking.Event.EventName);
            body = body.Replace("{Id}", booking.Event.EventId.ToString());
            body = body.Replace("{Location}", booking.Event.Location);
            body = body.Replace("{Date}", booking.Event.DateOfEvent.ToShortDateString());
            body = body.Replace("{Event}", booking.Event.EventName);
            body = body.Replace("{bookingId}", booking.Event.EventId.ToString());
            return body;



        }



        private String CreateCancelBody(Bookings booking)
        {

            String body = String.Empty;
            using (StreamReader reader = new StreamReader(Server.MapPath("~/Email Templates/Cancel.html")))
            {

                body = reader.ReadToEnd();

            }


            body = body.Replace("{Event}", booking.Event.EventName);
            body = body.Replace("{bookingId}", booking.Event.EventId.ToString());
            return body;



        }




        // GET: Booking/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Event.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Booking/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( [Bind(Include = "EventId,EventName,Location,DateOfEvent,FivekmRace,TenkmRace,HalfMarathon,FullMarathon,City,State,Country,EventType")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Event.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

Assignment 1/Views/Booking/Details.cshtml
@model Assignment_1.Models.BookingViewModel

@{
    ViewBag.Title = "EventRegistration";
    Layout = "~/Views/Shared/_searchlayout.cshtml";
}


<div class="page-slider" style="background-image:url(http://localhost:59345/Images/bg_13.jpg)">

    

</div>


<div class="container" style="margin-top:30px;">
    <h1 style="color:green;text-transform:uppercase">@Model.Event.EventName</h1>
    <hr />
    
    <div class="col-sm-6">


        @if (Model.Bookings == null)
        {
        <div class="col-sm-12">

            <h2> REGISTER </h2>

            </div>

            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-sm-12">
                <h4 style="margin-top:10px"> Select the type of event </h4>
                @Html.DropDownListFor(model => model.Bookings.RaceType, (SelectList)ViewBag.EventType, new { @class = "form-control  dropdown-event" })
                @Html.HiddenFor(model => model.Bookings.Event)

            </div>


            <div class="col-sm-12 5K" style="margin-top:30px;display:none">
                <p> The 5K run is a long-distance road running competition over a distance of five kilometres (3.107 miles). Also referred to as the 5K road race, 5 km, or simply 5K, it is the shortest of the most common road running distances.</p>
            </div>

            <div class="col-sm-12 10K" style="margin-top:30px;display:none">
                <p>The 10K run is a long-distance road running competition over a distance of ten kilometres (6.2 miles). Also referred to as the 10K road race, 10 km, or simply 10K, it is one of the most common types of road running event, alongside the shorter 5K and longer half marathon and marathon. It is usually distinguished from the 10,000 metres track running event by stating the distance in kilometres, rather than metres.</p>
            </div>

            <div class="col-sm-12 HM" style="margin-top:30px;display:none">
                <p>A half marathon is a road running event of 21.0975 km (13 mi 192½ yd)—half the distance of a marathon.[1] It is common for a half marathon event to be held concurrently with a marathon, using almost the same course with a late start, an early finish or shortcuts.</p>
            </div>

            <div class="col-sm-12 FM" style="margin-top:30px;display:none">
                <p>The marathon is a long-distance race, completed by running, walking, or a run/walk strategy. There are also wheelchair divisions. The marathon has an official distance of 42.195 kilometres (26.219 miles; 26 miles 385 yards),[1] usually run as a road race.</p> 
            </div>

            <div class="col-sm-12" style="margin-top:30px">
                <button class="btn btn-success" name="btn" value="@Model.Event.EventId" type="submit">BOOK NOW</button>
            </div>
             }

         }
        else
        {

            <div class="col-sm-12">
                
                <h3> REGISTRATION DETAILS </h3>

            </div>

            <div class="col-sm-12">

                @if (Model.Bookings.Status)
                {

                    <h4>
                        Booking status :
                        <span style="color:green">

                            ACTIVE <i class="fas fa-check"></i>

                        </span>
                    </h4>

                    <h4>
                        Booking ID :

                        <span>

                            @Model.Bookings.BookingId


                        </span>


                    </h4>

                    <h4>
                        Your Event:

                        <span>

                            @Model.Bookings.RaceType


                        </span>


                    </h4>



                    @Html.ActionLink("Cancel Booking", "Cancel", "Booking", new { id = Model.Event.EventId }, new { @class = "btn btn-success" })


                }
                else
                {
                    <h3>
                        Booking status :
                        <span style="color:brown">

                            CANCELLED <i class="fas fa-ban"></i>

                        </span>
                    </h3>
                }



            </div>
        }


    </div>

    <div class="col-sm-6" style="margin-top:10px;">

        <div class="col-sm-12">
            <h4><i class="fas fa-map-marker-alt"></i>  ADDRESS </h4>
            <h4> @Model.Event.Location </h4>
        </div>

        <div class="col-sm-12" style="margin-top:30px;">
            <h4><i class="far fa-calendar-alt"></i>  DATE </h4>
            <h4> @Model.Event.DateOfEvent.ToShortDateString() </h4>
        </div>

        <div class="col-sm-12" style="margin-top:30px;">

            @if (Model.Event.EventType == "1")
            {
                <h4><i class="fas fa-shoe-prints"></i> TYPE OF EVENT </h4>
                <h4> Community Run</h4>
            }
            else
            {
                <h4><i class="fas fa-shoe-prints"></i></h4>
                <h4> Professional Event</h4>
            }

        </div>

        <div class="col-sm-12" style="margin-top:30px;">

            <h4> AVAILABLE RACES </h4>

            <span>

                @if (Model.Event.FivekmRace)
                {

                    <span class="dot-green"></span><span> 5KM Race</span>


                }



                @if (Model.Event.TenkmRace)
                {

                    <span class="dot-red"></span>
                    <span>10 KM Race</span>


                }



                @if (Model.Event.HalfMarathon)
                {

                    <span class="dot-blue"> </span>
                    <span> Half Marathon</span>

                }


                @if (Model.Event.FullMarathon)
                {
                    <span class="dot-purple"></span>
                    <span> Full Marathon</span>
                }

            </span>

            </div>


    </div>
    
    



</div>

Assignment 1/Views/Booking/EventBooking.cshtml
@model IEnumerable<Assignment_1.Models.Bookings>

@{
    ViewBag.Title = "EventBooking";
    Layout = "~/Views/Shared/_searchlayout.cshtml";
}

<h2>EventBooking</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RaceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RaceType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookingId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookingId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookingId })
        </td>
    </tr>
}

</table>