Assignment 1/Models/RunnerProfile.cs
using Assignment_1.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Assignment_1.Models
{
    public class RunnerProfile
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProfileId { get; set; }

        [Required]
        [RegularExpression("[A-Za-z ]+", ErrorMessage = "Your first name should contain only alphabets")]
        public string FirstName { get; set; }

        [Required]
        [RegularExpression("[A-Za-z ]+", ErrorMessage = "Your  name should contain only alphabets")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        [AgeAttribute(18, ErrorMessage = "You must be 18 years old to use this app")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Column(TypeName = "datetime")]
        public DateTime DateOfBirth { get; set; }


        [Required]
        [Display(Name = "Height (in cms)")]
        [Range(30,240, ErrorMessage = "You must enter a valid height")]
        public double Height { get; set; }


        [Required]
        [Display(Name = "Weight (in cms)")]
        [Range(30, 400, ErrorMessage = "You must enter a valid weight" )]
        public double weight { get; set; }



        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

Assignment 1/Controllers/RunnerProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment_1.Models;
using Microsoft.AspNet.Identity;

namespace Assignment_1.Controllers
{
    [Authorize (Roles ="Runner")]
    public class RunnerProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: RunnerProfiles/Index/
        public ActionResult Index()
        {
            string Id = User.Identity.GetUserId();

            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RunnerProfile runnerProfile = db.RunnerProfile.Where(o => o.ApplicationUser.Id == Id).FirstOrDefault();

            if (runnerProfile == null)
            {
                return RedirectToAction("Create");
            }

            return View(runnerProfile);
        }



        // GET: RunnerProfiles/Create
        public ActionResult Create()
        {
            string Id = User.Identity.GetUserId();
            RunnerProfile runnerProfile = db.RunnerProfile.Where(o => o.ApplicationUser.Id == Id).FirstOrDefault();

            if (runnerProfile == null)
            {

                return View();
            }
            else
            {
                return RedirectToAction("Edit");
            }

        }



        // POST: RunnerProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProfileId,FirstName,LastName,DateOfBirth,Height,weight")] RunnerProfile runnerProfile)
        {
           if (ModelState.IsValid)
            {
                runnerProfile.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
                db.RunnerProfile.Add(runnerProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(runnerProfile);
        }



        // GET: RunnerProfiles/Edit
        public ActionResult Edit()
        {
            string Id = User.Identity.GetUserId();
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RunnerProfile runnerProfile = db.RunnerProfile.Where(o => o.ApplicationUser.Id == Id).FirstOrDefault();

            if (runnerProfile == null)
            {
                return RedirectToAction("Create");
            }

            return View(runnerProfile);
        }



        // POST: RunnerProfiles/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProfileId,FirstName,LastName,DateOfBirth,Height,weight")] RunnerProfile runnerProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(runnerProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(runnerProfile);
        }



        // Delete and delete confirmed needs to be implemented with views

        // GET: RunnerProfiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RunnerProfile runnerProfile = db.RunnerProfile.Find(id);
            if (runnerProfile == null)
            {
                return HttpNotFound();
            }
            return View(runnerProfile);
        }

        // POST: RunnerProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RunnerProfile runnerProfile = db.RunnerProfile.Find(id);
            db.RunnerProfile.Remove(runnerProfile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment 1/Views/RunnerProfiles/Create.cshtml
@model Assignment_1.Models.RunnerProfile

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_dateLayout.cshtml";
}

<div class="container" style="margin-top:50px">



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h3>CREATE PROFILE</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control color-green" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control color-green" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @{ Html.EnableClientValidation(false); }
                @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control date-picker color-green" } })
                    @{ Html.EnableClientValidation(true); }
                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control color-green" } })
                    @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control color-green" } })
                    @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-2">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }


</div>

Assignment 1/Views/RunnerProfiles/Edit.cshtml
@model Assignment_1.Models.RunnerProfile

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_dateLayout.cshtml";
}


<div class="container" style="margin-top:50px">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h3>
                EDIT PROFILE </h3>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ProfileId)

                <div class="form-group" style="margin-top:40px">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control col-sm-10 color-green" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="margin-top:30px">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control col-sm-10 color-green" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="margin-top:30px">
                    @{ Html.EnableClientValidation(false); }
                    @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control date-picker col-sm-10 color-green" } })
                        @{ Html.EnableClientValidation(true); }
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="margin-top:30px">
                    @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control col-sm-10 color-green" } })
                        @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="margin-top:30px">
                    @Html.LabelFor(model => model.weight, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control col-sm-10 color-green" } })
                        @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="margin-top:30px">
                    <div class="col-md-offset-2 col-sm-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
        </div>
    }

   



</div>

Assignment 1/Views/RunnerProfiles/Index.cshtml
@model Assignment_1.Models.RunnerProfile

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_dateLayout.cshtml";
}


<div class="container">



    <h3 style="margin-top:50px"> PROFILE </h3>
    <hr />
    <!--
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

    </dl>

        -->

    <div class="row" style="margin-top:30px">
        <span class="col-md-3 col-sm-3">  @Html.DisplayNameFor(model => model.FirstName)  </span>
        <span class="col-sm-9 col-md-9">  : @Html.DisplayFor(model => model.FirstName)  </span>
    </div>

    <div class="row" style="margin-top:30px">
        <span class="col-md-3 col-sm-3">  @Html.DisplayNameFor(model => model.LastName)  </span>
        <span class="col-sm-9 col-md-9"> :  @Html.DisplayFor(model => model.LastName)  </span>
    </div>

    <div class="row" style="margin-top:30px">
        <span class="col-md-3 col-sm-3">  @Html.DisplayNameFor(model => model.DateOfBirth)  </span>
        <span class="col-sm-9 col-md-9">  : @Html.DisplayFor(model => model.DateOfBirth)  </span>
    </div>

    <div class="row" style="margin-top:30px">
        <span class="col-md-3 col-sm-3">  @Html.DisplayNameFor(model => model.Height)  </span>
        <span class="col-sm-9 col-md-9">  : @Html.DisplayFor(model => model.Height)  </span>
    </div>

    <div class="row" style="margin-top:30px">
        <span class="col-md-3 col-sm-3">  @Html.DisplayNameFor(model => model.weight)  </span>
        <span class="col-sm-9 col-md-9">  : @Html.DisplayFor(model => model.weight)  </span>
    </div>


    <div class=" col-md-1  col-sm-1" style="margin-top:40px">
        @Html.ActionLink("Edit", "Edit", "RunnerProfiles", null, new { @class = "btn btn-success" })
    </div>

</div>